### ISSUE TITLE
synchronization state not saved while first pulling

### ISSUE THREAD

**Issue by yeled** [gauteh/gmailieer#11]
I have a lot of email, and syncing for the first time is a problem, due to Gmail throttling.

I try to cancel the first run, to get reset at the Gmail end and avoid the throttling, but I'm back in the first situation again, and I will end up with duplicate files on disk:

```
(venv) 20:13 CHARLIE~/Maildir/charlie@XXX.com[!!venv@3.5.2] % PYTHONPATH=~/src/notmuch/bindings/python/  ~/src/gmailieer/gmi pull    (chp02-rsvp|✚23…)
pull: full synchronization (no previous synchronization state)
fetching messages: 557143it [19:02, 487.47it/s]
receiving content :   0%|                                                                                             | 129/557143 [00:17<13:22:16, 11.57it/s]
reducing batch request size to: 100
reducing batch request size to: 50
receiving content :  30%|██████████████████████████▎                                                              | 164746/557143 [4:08:49<9:26:39, 11.54it/s]
reducing batch request size to: 25

^Creceiving content :  34%|██████████████████████████████▎                                                          | 190047/557143 [5:23:08<9:19:35, 10.93it/
s]Traceback (most recent call last):
  File "/Users/charlie/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 272, in pull
    self.full_pull ()
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 488, in full_pull
    updated = self.get_content (message_ids)
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 556, in get_content
    self.remote.get_messages (need_content, _got_msg, 'raw')
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 82, in func_wrap
    return func (self, *args, **kwargs)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 204, in get_messages
    batch.execute (http = self.http)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 1417, in execute
    self._execute(http, self._order, self._requests)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/googleapiclient/http.py", line 1349, in _execute
    headers=headers)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.5/site-packages/httplib2/__init__.py", line 1054, in _conn_request
    content = response.read()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 455, in read
    return self._readall_chunked()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 561, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 607, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
```

Then I try again, without the throttle:

```
(venv) 9:26 CHARLIE~/Maildir/charlie@XXX.com[!!venv@3.5.2] % PYTHONPATH=~/src/notmuch/bindings/python/  ~/src/gmailieer/gmi pull     (chp02-rsvp|✚23…)
pull: full synchronization (no previous synchronization state)
fetching messages:  24%|███████████████████████▊                                                                          | 800/3296 [00:02<00:05, 430.98it/s]
```

Can we sync state during the initial pull, and then resume the pull?

**Comment by yeled** [comment]
I think I'm wrong. I cancelled one pull at `206841/367529` and it resumed at `192/160861`.

**Comment by gauteh** [comment]
Yeah, it should detect which messages have been pulled. A first full
list of messages is necessary to feth again though. I do not see any
other way to ensure that no messages are lost (e.g. if some messages are
changed online in the mean time).

Regards, Gaute
