### ISSUE TITLE
Database object has no attribute get_revision

### ISSUE THREAD

**Issue by aureooms** [gauteh/gmailieer#14]
```
pull: full synchronization (no previous synchronization state)
fetching messages: 7479it [00:16, 322.74it/s]                                                                                                                                                  
receiving content: everything up-to-date.
receiving metadata:  59%|████████████████████████████████████████████████████████████████████████████▍                                                     | 4401/7479 [00:47<00:34, 88.41it/s]
reducing batch request size to: 100
receiving metadata: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7479/7479 [01:22<00:00, 90.88it/s]
Traceback (most recent call last):
  File "/home/aureooms/.bin/gmi", line 8, in <module>
    g.main ()
  File "/home/aureooms/.opt/gmailieer/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/home/aureooms/.opt/gmailieer/lieer/gmailieer.py", line 272, in pull
    self.full_pull ()
  File "/home/aureooms/.opt/gmailieer/lieer/gmailieer.py", line 499, in full_pull
    (rev, uuid) = db.get_revision ()
AttributeError: 'Database' object has no attribute 'get_revision'
```

**Comment by gauteh** [comment]
Aurélien Ooms writes on april 28, 2017 3:00:
> ```
>   File "/home/aureooms/.opt/gmailieer/lieer/gmailieer.py", line 499, in full_pull
>     (rev, uuid) = db.get_revision ()
> AttributeError: 'Database' object has no attribute 'get_revision'
> ```

You need notmuch with python bindings newer than 0.24.

**Comment by aureooms** [comment]
Ok!

**Comment by aureooms** [comment]
I have 0.24.1 installed. The change was pushed on master on [March 10](https://notmuchmail.org/pipermail/notmuch/2017/024236.html). Is it not yet released?

```
$ yaourt notmuch          
1 community/notmuch 0.24.1-2 [installed]
    Notmuch is not much of an email program
```

**Comment by gauteh** [comment]
Maybe you have old python bindings?

**Comment by aureooms** [comment]
Works with aur/notmuch-git however.

**Comment by aureooms** [comment]
The bindings are in the same package, aren't they?

**Comment by gauteh** [comment]
I don't know, I'm not using the package.

**Comment by gauteh** [comment]
Maybe there's a problem with the package.
