### ISSUE TITLE
muted tag is invalid to push

### ISSUE THREAD

**Issue by yeled** [gauteh/gmailieer#18]
```
pushing, 0 changed:   0%|                                                                                                                                                               | 0/162 [00:00<?, ?it/s]
push: creating label: muted..
Traceback (most recent call last):
  File "/Users/charlie/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 186, in sync
    self.push (args, True)
  File "/Users/charlie/src/gmailieer/lieer/gmailieer.py", line 224, in push
    r = self.remote.update (m, self.local.state.last_historyId, self.force)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 83, in func_wrap
    return func (self, *args, **kwargs)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 376, in update
    self.__push_tags__ (mid, add, rem)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 83, in func_wrap
    return func (self, *args, **kwargs)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 396, in __push_tags__
    (lid, ll) = self.__create_label__ (a)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 83, in func_wrap
    return func (self, *args, **kwargs)
  File "/Users/charlie/src/gmailieer/lieer/remote.py", line 433, in __create_label__
    lr = self.service.users ().labels ().create (userId = self.account, body = label).execute ()
  File "/Users/charlie/src/gmailieer/venv/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/charlie/src/gmailieer/venv/lib/python3.6/site-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/charlie%40eatyourpets.com/labels?alt=json returned "Invalid label name">
pushing, 0 changed:   1%|▉                                                                                                                                                      | 1/162 [00:00<00:30,  5.24it/s]
```

Apparently, `muted` [isn't available](http://stackoverflow.com/questions/28248966/muting-with-the-gmail-api) in the API!

I can add it to `ignore_labels` in `local.py` but we should note in the README that syncing muting isn't supported.

**Comment by gauteh** [comment]
Charlie Allom writes on mai 3, 2017 9:12:
> Apparently, `muted` [isn't available](http://stackoverflow.com/questions/28248966/muting-with-the-gmail-api) in the API!
> 
> I can add it to `ignore_labels` in `local.py` but we should note in the README that syncing muting isn't supported.

Yep!

**Comment by yeled** [comment]
Will do. Interestingly, google has accepted the bug report this year! https://issuetracker.google.com/issues/36759067
