### ISSUE TITLE
lieer.remote.GenericException: no 'history' record returned, even though several pages were indicated.

### ISSUE THREAD

**Issue by julian-klode** [gauteh/gmailieer#24]
Note sure what happened. I was removing the inbox tag on about 30 messages or so, and then syncing.

```push: everything is up-to-date.
pull: partial synchronization.. (hid: 12008538)
fetching changes: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/jak/Downloads/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/home/jak/Downloads/gmailieer/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/home/jak/Downloads/gmailieer/lieer/gmailieer.py", line 190, in sync
    self.pull (args, True)
  File "/home/jak/Downloads/gmailieer/lieer/gmailieer.py", line 315, in pull
    self.partial_pull ()
  File "/home/jak/Downloads/gmailieer/lieer/gmailieer.py", line 324, in partial_pull
    for hist in self.remote.get_history_since (self.local.state.last_historyId):
  File "/home/jak/Downloads/gmailieer/lieer/remote.py", line 166, in get_history_since
    raise Remote.GenericException ("no 'history' record returned, even though several pages were indicated.")
lieer.remote.GenericException: no 'history' record returned, even though several pages were indicated.
fetching changes: 100it [00:00, 607.63it/s]
```

**Comment by gauteh** [comment]
Same as #22.

**Comment by gauteh** [comment]
Can you try again a few times and see if it resolves itself?

**Comment by gauteh** [comment]
https://stackoverflow.com/questions/44276743/gmail-api-users-history-list-returns-nextpagetoken-but-no-history-field

**Comment by gauteh** [comment]
Try latest master.

**Comment by julian-klode** [comment]
Oh, it resolved itself as soon as I made any change in the gmail web UI, and it did not happen again after that, so it's a bit weird.

**Comment by gauteh** [comment]
Julian Andres Klode writes on mai 31, 2017 11:48:
> Oh, it resolved itself as soon as I made any change in the gmail web UI, and it did not happen again after that, so it's a bit weird. 
> 

Yeah - I think it is a gmail api bug, so its bound to be erratic.
Closing for now.

-g

**Comment by gauteh** [comment]
Reference: gmail issue: https://issuetracker.google.com/issues/62686910
