### ISSUE TITLE
Assertion Error status=count(messages)- can't really pinpoint the source

### ISSUE THREAD

**Issue by nv1t** [gauteh/gmailieer#30]
I can pull message, but not push. 
Using the current HEAD, notmuch in git package version in Arch

During push an Assertion Error kills the script
```-> % gmi sync
Traceback (most recent call last):
  File "/usr/bin/gmi", line 4, in <module>
    __import__('pkg_resources').run_script('gmailieer==0.1', 'gmi')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/gmailieer-0.1-py3.6.egg/EGG-INFO/scripts/gmi", line 8, in <module>
  File "/usr/lib/python3.6/site-packages/gmailieer-0.1-py3.6.egg/lieer/gmailieer.py", line 136, in main
  File "/usr/lib/python3.6/site-packages/gmailieer-0.1-py3.6.egg/lieer/gmailieer.py", line 186, in sync
  File "/usr/lib/python3.6/site-packages/gmailieer-0.1-py3.6.egg/lieer/gmailieer.py", line 213, in push
  File "/usr/lib/python3.6/site-packages/notmuch/query.py", line 204, in count_messages
    raise NotmuchError(status)
  File "/usr/lib/python3.6/site-packages/notmuch/errors.py", line 129, in __new__
    subclass = cls.get_exc_subclass(status)  # which class to use?
  File "/usr/lib/python3.6/site-packages/notmuch/errors.py", line 115, in get_exc_subclass
    assert 0 < status <= len(subclasses)
AssertionError
```

status seems like the count of my messages: ~22k, and len(subclasses): 14, 

The Function in count_messages in "notmuch/query.py" tries to count messages and should give a status back, But it seems, the status is the message count.
It seems the python script doesn't match with the notmuch library.

``` 
def count_messages(self):
        '''
        This function performs a search and returns Xapian's best
        guess as to the number of matching messages.

        :returns: the estimated number of messages matching this query
        :rtype:   int
        '''
        self._assert_query_is_initialized()
        count = c_uint(0)
        status = Query._count_messages(self._query, byref(count))
        if status != 0:
            raise NotmuchError(status)
        return count.value
```

If see the problem in the packaging of notmuch as well, you can close this issue.

**Comment by gauteh** [comment]
This could be a mismatch between python bindings version and notmuch
library, if not it is a notmuch bug.

**Comment by nv1t** [comment]
ahhh...they bumped a version up 8 days ago...well...that could be. ok. it has apparently nothing to do with gmailieer. I'll close this :)

**Comment by gauteh** [comment]
Ok!


fre. 9. jun. 2017 kl. 18.14 skrev nv1t <notifications@github.com>:
