### ISSUE TITLE
Initial pull fails with KeyError

### ISSUE THREAD

**Issue by tadfisher** [gauteh/gmailieer#46]
Output:

```
pull: full synchronization (no previous synchronization state)
fetching messages: 353225it [18:57, 310.48it/s]                                 
receiving content:  73%|████████▋   | 257019/353225 [6:17:36<2:56:26,  9.09it/s]Traceback (most recent call last):
  File "/usr/bin/gmi", line 8, in <module>
    g.main ()
  File "/usr/lib/python3.6/site-packages/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/usr/lib/python3.6/site-packages/lieer/gmailieer.py", line 307, in pull
    self.full_pull ()
  File "/usr/lib/python3.6/site-packages/lieer/gmailieer.py", line 527, in full_pull
    updated = self.get_content (message_gids)
  File "/usr/lib/python3.6/site-packages/lieer/gmailieer.py", line 592, in get_content
    self.remote.get_messages (need_content, _got_msg, 'raw')
  File "/usr/lib/python3.6/site-packages/lieer/remote.py", line 106, in func_wrap
    return func (self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/lieer/remote.py", line 277, in get_messages
    batch.execute (http = self.http)
  File "/usr/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 1464, in execute
    self._callback(request_id, response, exception)
  File "/usr/lib/python3.6/site-packages/lieer/remote.py", line 257, in _cb
    cb (resp)
  File "/usr/lib/python3.6/site-packages/lieer/gmailieer.py", line 590, in _got_msg
    self.local.store (m, db)
  File "/usr/lib/python3.6/site-packages/lieer/local.py", line 343, in store
    self.update_tags (m, p, db)
  File "/usr/lib/python3.6/site-packages/lieer/local.py", line 351, in update_tags
    labels = [self.gmailieer.remote.labels[l] for l in labels]
  File "/usr/lib/python3.6/site-packages/lieer/local.py", line 351, in <listcomp>
    labels = [self.gmailieer.remote.labels[l] for l in labels]
KeyError: 'Label_9'
```

**Comment by gauteh** [comment]
Did you by any chance create a label online while pulling?

**Comment by gauteh** [comment]
Closing untill more info.
