### ISSUE TITLE
Can't initialize

### ISSUE THREAD

**Issue by LawsonJohnson** [gauteh/gmailieer#47]
I get this error when trying to run init; creating the file results in gmi saying that \'.gmailieer.json\' exists: this repository seems to already be set up.

>username@computername:~/.mail> gmi init myusername@gmail.com
initializing repository in: /home/username/.mail..
Traceback (most recent call last):
  File "/usr/bin/gmi", line 4, in <module>
    __import__('pkg_resources').run_script('gmailieer==0.3', 'gmi')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/gmailieer-0.3-py3.6.egg/EGG-INFO/scripts/gmi", line 8, in <module>
  File "/usr/lib/python3.6/site-packages/gmailieer-0.3-py3.6.egg/lieer/gmailieer.py", line 136, in main
  File "/usr/lib/python3.6/site-packages/gmailieer-0.3-py3.6.egg/lieer/gmailieer.py", line 140, in initialize
  File "/usr/lib/python3.6/site-packages/gmailieer-0.3-py3.6.egg/lieer/local.py", line 199, in initialize_repository
  File "/usr/lib/python3.6/site-packages/gmailieer-0.3-py3.6.egg/lieer/local.py", line 81, in write
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.mail/.gmailieer.json'

**Comment by gauteh** [comment]
Lawson Johnson writes on november 14, 2017 18:57:
> I get this error when trying to run init; creating the file results in gmi saying that \'.gmailieer.json\' exists: this repository seems to already be set up.
> 

Hi, please try latest master. Hopefully fixed there.

- gaute

**Comment by gauteh** [comment]
Assuming this is fixed.
