### ISSUE TITLE
Error while syncing cleaned up inbox

### ISSUE THREAD

**Issue by ktf** [gauteh/gmailieer#50]
I removed some 4000 emails on Gmail side (i.e. emptying trash) and when I do a sync I occasionally get the following:

```
Traceback (most recent call last):
  File "/nix/store/q1khwyfbip46yyddm0li2fsn0c3y9mx4-python3.6-gmaileer-v0.3-20171115/bin/.gmi-wrapped", line 9, in <module>
    g.main ()
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/lieer/gmailieer.py", line 136, in main
    args.func (args)
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/lieer/gmailieer.py", line 190, in sync
    self.pull (args, True)
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/lieer/gmailieer.py", line 315, in pull
    self.partial_pull ()
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/lieer/gmailieer.py", line 457, in partial_pull
    self.local.remove (m['id'], db)
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/lieer/local.py", line 298, in remove
    nmsg  = db.find_message_by_filename (fname)
  File "/nix/store/raxsnrd51a6j0f8qpmi3f4ri1lx4r0p4-python3-3.6.2-env/lib/python3.6/site-packages/notmuch/database.py", line 560, in find_message_by_filename
    raise NotmuchError(status)
notmuch.errors.XapianError
```

**Comment by gauteh** [comment]
hm.. any chance of putting in some try catch to get the status from notmucherror? have you run `notmuch new` or modified the notmuch db using a MUA or notmuch cli outside gmailieer while the pull is running?

**Comment by gauteh** [comment]
Need some more info on this one, otherwise will close. This error often happens if the notmuch db has been modified externally of gmailieers open DB instance.

**Comment by gauteh** [comment]
Closing, please re-open if you have more info.

**Comment by tabuchid** [comment]
@gauteh I'm hitting something similar and I believe I did modify the notmuch db using a client (emacs) while a pull was running. This then locked up and I killed the process which I believe put me in a dirty state. How do I recover?

**Comment by gauteh** [comment]
You can try to do 'gmi pull -f', it will take some time. and reset everything to remote state
