### ISSUE TITLE
Problems using notmuch database on a path containing symbolic links

### ISSUE THREAD

**Issue by francesquini** [gauteh/gmailieer#67]
For some reasons particular to my setup, my notmuch database is configured using a path containing a symbolic link. Notmuch does not complain about that and works like a charm. 

However, gmailieer does not like symbolic links and always tries to use the real path to the database. 

https://github.com/gauteh/gmailieer/blob/f610557c2964e1e3c628e04276b45d20c8ba7066/lieer/local.py#L145

Even if the paths are logically the same, the real path string is evidently different from the path (that contains the symbolic link) that I configured notmuch with. Thus I always, incorrectly ,get  the following message.

```local mail repository not in notmuch db```

For the time being I created a script that, using sed, alters notmuch configuration and after gmailieer is done goes back to the original configuration. It is not ideal, but works for me.

I was wondering, could the code above be altered to try and match the symbolic link path with the absolute one?

**Comment by gauteh** [comment]
Hm - I think that full path is required for that function and to be sure that it is unique, but it probably does not need to be `abspath`. `self.md` is based on current working directory, which is not necessarily a full path (as far as I know.. ?)

**Comment by francesquini** [comment]
Well, I tried to do the obvious thing (i.e., removing the call to `os.path.abspath`), but it still get the same error, apparently caused by the return of the `db.get_directory` call. Maybe notmuch library itself might be doing something similar to unequivocally identify the database location.

**Comment by gauteh** [comment]
Emilio Francesquini writes on april 2, 2018 13:38:
> Well, I tried to do the obvious thing (i.e., removing the call to `os.path.abspath`), but it still get the same error, apparently caused by the return of the `db.get_directory` call. Maybe notmuch library itself might be doing something similar to unequivocally identify the database location.
> 

This could work:

1. Get full symlinked (configured) path to db root (including root /)
2. Get absolute gmailieer folder
3. Get absolute db-path from 1.
4. Subtract 2. from 3. to get relative path to full symlinked path
5. Construct full path by adding 4. to 1.

**Comment by gauteh** [comment]
Gaute Hope writes on april 2, 2018 20:41:
> Emilio Francesquini writes on april 2, 2018 13:38:
>> Well, I tried to do the obvious thing (i.e., removing the call to `os.path.abspath`), but it still get the same error, apparently caused by the return of the `db.get_directory` call. Maybe notmuch library itself might be doing something similar to unequivocally identify the database location.
>> 
> 
> This could work:
> 
> 1. Get full symlinked (configured) path to db root (including root /)
> 2. Get absolute gmailieer folder
> 3. Get absolute db-path from 1.
> 4. Subtract 2. from 3. to get relative path to full symlinked path
> 5. Construct full path by adding 4. to 1.

This won't work if the gmailieer folder is symlinked in from somewhere 
else again inside the symlinked db root.. so should check and bail if 
this does not resolve to the same folder in the end.

**Comment by gauteh** [comment]
Are you calling gmi from the symlinked dir or from the absolute dir?

**Comment by gauteh** [comment]
Going to close unless get more info.

**Comment by Cybolic** [comment]
I had the same issue when running gmi from within the symlinked dir.

I fixed it by changing `os.getcwd()` to `os.getenv('PWD')`.

**Comment by Emiller88** [comment]
This is still an bug @gauteh in case you missed @Cybolic 's message. At least in the version in the Ubuntu repos.

**Comment by Cybolic** [comment]
For what it's worth, I'm using the AUR package (on Arch, obviously) that pulls here from the git repo, so it's not linked to the distro.

**Comment by stdbull** [comment]
Hi @gauteh 
Some time has passed on this and I have hit the same problem described above, and the same solution/change from @Cybolic  works for me. Here it is:

```
diff --git a/lieer/local.py b/lieer/local.py
index a9c6a75..dbc68d1 100644
--- a/lieer/local.py
+++ b/lieer/local.py
@@ -266,7 +266,7 @@ class Local:
 
   def __init__ (self, g):
     self.gmailieer = g
-    self.wd = os.getcwd ()
+    self.wd = os.getenv('PWD')
     self.dry_run = g.dry_run
 
     # config and state files for local repository
```
This occurred because I moved my mail store from outside $home into $home (longer story is because I set up a new machine with BTRFS and wanted to include my mail store in my @home sub volume so it was included in those snapshots).

**Old set up (no sym link):**
~/.notmuch-config
[database]
path=/topleveldir/path/to/mail

lieer top level directory at:
/topleveldir/path/to/mail/gmailieer

All has been good for years :-)

**New set up (with sym link):**
~/.notmuch-config
[database]
path=/topleveldir/path/to/mail

Symlink is now shown by ls -l /
topleveldir -> /home/me/topleveldir

lieer top level directory at:
/home/me/topleveldir/path/to/mail/gmailieer

With the new set up (with sym link), any gmi operation within /topleveldir/path/to/mail/gmailieer results in:

>   File "/home/me/git/lieer/lieer/local.py", line 312, in load_repository
>     raise Local.RepositoryException ("local mail repository not in notmuch db")
> lieer.local.RepositoryException: local mail repository not in notmuch db
> 

If I make the one liner change above, it works fine.

Is it possible for you to reproduce this and push a fix to the repo?

Cheers,
--  Matt

**Comment by gauteh** [comment]
Hi, this solution will probably not work with the `-C` option, there are also some other pitfalls - e.g. shell dependence: https://stackoverflow.com/questions/1542803/is-there-a-version-of-os-getcwd-that-doesnt-dereference-symlinks - might be dependent on how gmi is launched (maybe from another program that was never launched by a shell).

**Comment by gauteh** [comment]
A solution would have to fall-back to using `os.getcwd()` at least if `PWD` is not set. Should also check if PWD and `getcwd` deref to the same path (in case of `-C`).

**Comment by stdbull** [comment]
Ok, thanks. In the end, I just changed ~/.notmuch-config to make the database section point to the new mail store location (inside HOME). Notmuch realised that the paths to the emails were in fact identical, so notmuch new didn't have much to do at all ;-)
Now gmi is fine with me using the new mail store location inside home (and I can use -C).
I have hit another problem though using gmi pull inside notmuch-hooks (5) in the pre-new hook. I will try to figure that out some more (but it looks the database is locked, so gmi pull hangs).
Thanks again for the quick support.

**Comment by laur89** [comment]
Can this be reopened?

Have symlink `~/mail -> /data/mail-test` & notmuch/database.path = path=/home/laur89/mail

First attempting to symlink from a random dir:
```sh
@ /tmp:
$ gmi pull -C ~/mail
path: /home/laur89/mail/
Traceback (most recent call last):
  File "/usr/share/lieer/lieer/local.py", line 371, in load_repository
    self.nm_relative = str(Path(self.md).relative_to(db.path))
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 385, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/data/mail-test/mail' is not in the subpath of '/home/laur89/mail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gmi", line 24, in <module>
    g.main ()
    ~~~~~~~^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 419, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 612, in pull
    self.setup(args, args.dry_run, True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 489, in setup
    self.local.load_repository(block)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/share/lieer/lieer/local.py", line 373, in load_repository
    raise Local.RepositoryException(
        "local mail repository not in notmuch db"
    )
lieer.local.Local.RepositoryException: local mail repository not in notmuch db
```

Same issue when cd-ing to `~/mail`:
```sh
@ ~/mail:
$ gmi pull
Traceback (most recent call last):
  File "/usr/share/lieer/lieer/local.py", line 371, in load_repository
    self.nm_relative = str(Path(self.md).relative_to(db.path))
                           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 385, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/data/mail-test/mail' is not in the subpath of '/home/laur89/mail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gmi", line 24, in <module>
    g.main ()
    ~~~~~~~^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 419, in main
    args.func(args)
    ~~~~~~~~~^^^^^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 612, in pull
    self.setup(args, args.dry_run, True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/lieer/lieer/gmailieer.py", line 489, in setup
    self.local.load_repository(block)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/share/lieer/lieer/local.py", line 373, in load_repository
    raise Local.RepositoryException(
        "local mail repository not in notmuch db"
    )
lieer.local.Local.RepositoryException: local mail repository not in notmuch db
```
---

Running lieer `1.6-6`, installed from debian testing repos.
