### ISSUE TITLE
"sent" label is not synced back

### ISSUE THREAD

**Issue by mjg** [gauteh/gmailieer#68]
Apparently, the "sent" label (pseudo label) is only synced from GMail to the notmuch database, not vice versa:

If I send an e-mail using GMail's web interface (or IMAP) it gets saved by GMail and appears under "sent messages"; when synced by gmailieer, it gets the notmuch tag "sent". So far so good.

If I tag a message as sent using "notmuch tag +sent" it gets the tag, and gmailieer seems to update something on sync but the message does not appear under "sent messages" in GMail (only "all mail").

I know that "sent" is not quite a label for GMail but something else - but maybe it could be synced both ways nonetheless?

[Background: I sometimes send using none-GMail-SMTP servers and want to mbsync (via IMAP) a copy of the sent message to my GMail account; this works fine, but I can't tag the copy as sent (i.e. sync the sent label) using gmailieer.]

**Comment by julian-klode** [comment]
Just a quick note: That's adding a new email, and that's not supported right now.

**Comment by julian-klode** [comment]
Just a quick note: That's adding a new email, and that's not supported right now.

**Comment by mjg** [comment]
> That's adding a new email,

Not, it is not. The e-mail is added via IMAP to the GMail account (the google servers), and gmailieer syncs the message happily from there. (What is not supported is adding a message to the maildir or notmuch-inserting it.)

The issue with the sent label is completely independent of how that e-mail arrives on the google servers (sent by someone else; copied via IMAP).

**Comment by gauteh** [comment]
Is it possible to add the sent label using the GMail web interface?

**Comment by mjg** [comment]
"sent" cannot be set as a label directly - just like inbox,spam, unread etc. It is search for as "in:sent" (just like "in:spam", not quite like "is:unread"). Those other system labels can bet set by other means (move to inbox, mark as spam, mark as unread).

I've found the lines in the code now that treat "sent" and "draft" as read-only labels and tags. If I remove "sent" from that list and try to sync a "sent" label I get:
```
Traceback (most recent call last):
  File "/home/mjg/.local/bin/gmi", line 4, in <module>
    __import__('pkg_resources').run_script('gmailieer==0.6', 'gmi')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(script_code, namespace, namespace)
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/EGG-INFO/scripts/gmi", line 8, in <module>
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/gmailieer.py", line 143, in main
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/gmailieer.py", line 193, in sync
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/gmailieer.py", line 269, in push
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/remote.py", line 110, in func_wrap
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/remote.py", line 607, in push_changes
  File "/usr/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 1464, in execute
    self._callback(request_id, response, exception)
  File "/home/mjg/.local/lib/python3.6/site-packages/gmailieer-0.6-py3.6.egg/lieer/remote.py", line 576, in _cb
NameError: name 'gids' is not defined
```

So, this seems to be a hard limitation on GMail's side that gmailieer can't work around, of course. Maybe it's worth documenting?

**Comment by gauteh** [comment]
Yes. Should be added to caveats in readme.

lør. 31. mar. 2018 kl. 11:40 skrev Michael J Gruber <
notifications@github.com>:
