### ISSUE TITLE
Ability to control logging output

### ISSUE THREAD

**Issue by stdbull** [gauteh/gmailieer#72]
Hi. I've used offlineimap for my personal email for a few years now and have recently switched to gmailieer for my gmail account. It's great! Thank you for all the hard work. I also run offlineimap on a system I created at work to harvest email and I would like to switch this to gmailieer too. The periodic mail sync on that machine is driven by cron. Offlineimap is configured on that machine to log to syslog. Since cron treats anything written to stdout as something it needs to notify me about, using gmailieer would incur me receiving email from this machine every mail sync cycle unless I do some redirect tweaking/hacking :-)
Offlineimap offers the ability to use a few different schemes for logging, eg syslog, tty and offers a quiet option too. I really like the gmailieer feedback using tqdm but would it be possible to introduce some sort of logging redirection, maybe just sending stdout to syslog? In that case, maybe the progress bar feedback wouldn't be as important.
Cheers,
--  Matt

**Comment by gauteh** [comment]
Hi, this should definitely be possible. We should have a --quiet option, and a --no-progress option (which also is enabled if tqdm is not available). Then it should be possible to use e.g. the `logger` command to redirect the output to syslog. Would that work for you? (then we don't have to mess around with syslog directly, just stdout)

**Comment by gauteh** [comment]
Could you test #73 ?

**Comment by stdbull** [comment]
Hi. I checked out origin/nobar with HEAD @ e2548d and did a sync using -s. Output was different, but the sync was not successful. See trace below:
`matt@sunrise:~/mail/personal$ gmi sync -s
receiving metadata (2) ...done: 2 its in 00.271s
resolving changes (2) ...done: 2 its in 00.001s
push: nothing to push
remote historyId: 889819
pull: partial synchronization.. (hid: 887252)
fetching changes ...done: 2 its in 00.295s
resolving changes (180) .....................done: 180 its in 00.007s
receiving content (25) .....done: 25 its in 02.395s
Traceback (most recent call last):
  File "/usr/local/bin/gmi", line 8, in <module>
    g.main ()
  File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 145, in main
    args.func (args)
  File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 215, in sync
    self.pull (args, True)
  File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 341, in pull
    self.partial_pull ()
  File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 482, in partial_pull
    for m in tqdm (deleted_messages, leave = True, desc = 'removing messages'):
TypeError: __init__() got multiple values for argument 'leave'
`

**Comment by gauteh** [comment]
Matthew Lear writes on april 5, 2018 20:51:
> Hi. I checked out origin/nobar with HEAD @ e2548d and did a sync using -s. Output was different, but the sync was not successful. See trace below:
> `matt@sunrise:~/mail/personal$ gmi sync -s
> receiving metadata (2) ...done: 2 its in 00.271s
> resolving changes (2) ...done: 2 its in 00.001s
> push: nothing to push
> remote historyId: 889819
> pull: partial synchronization.. (hid: 887252)
> fetching changes ...done: 2 its in 00.295s
> resolving changes (180) .....................done: 180 its in 00.007s
> receiving content (25) .....done: 25 its in 02.395s
> Traceback (most recent call last):
>   File "/usr/local/bin/gmi", line 8, in <module>
>     g.main ()
>   File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 145, in main
>     args.func (args)
>   File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 215, in sync
>     self.pull (args, True)
>   File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 341, in pull
>     self.partial_pull ()
>   File "/home/matt/git/gmailieer/lieer/gmailieer.py", line 482, in partial_pull
>     for m in tqdm (deleted_messages, leave = True, desc = 'removing messages'):
> TypeError: __init__() got multiple values for argument 'leave'

Should be fixed now - please try again.

**Comment by stdbull** [comment]
Indeed it is. sync worked fine with -s. Let me know if you'd like me to try any other logging / redirection changes.

**Comment by gauteh** [comment]
Matthew Lear writes on april 6, 2018 11:09:
> Indeed it is. sync worked fine with -s. Let me know if you'd like me to try any other logging / redirection changes. 
> 

The best would be if you could try it in your setup with either `logger` 
or some redirection to file or through cat.

**Comment by gauteh** [comment]
Gaute Hope writes on april 6, 2018 11:29:
> Matthew Lear writes on april 6, 2018 11:09:
>> Indeed it is. sync worked fine with -s. Let me know if you'd like me to try any other logging / redirection changes. 
>> 
> 
> The best would be if you could try it in your setup with either `logger` 
> or some redirection to file or through cat.

Merged into master.
