### ISSUE TITLE
batch request size == 0?

### ISSUE THREAD

**Issue by mturquette** [gauteh/gmailieer#79]
Hello,

My cron job that calls gmi (and does some mail tagging) has lately started failing with like so:

```
reducing batch request size to: 12
reducing batch request size to: 6
reducing batch request size to: 3
reducing batch request size to: 1
reducing batch request size to: 0
Traceback (most recent call last):
  File "/Users/mturquette/src/gmailieer/lieer/remote.py", line 291, in get_messages
    batch.execute (http = self.http)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/googleapiclient/http.py", line 1466, in execute
    self._callback(request_id, response, exception)
  File "/Users/mturquette/src/gmailieer/lieer/remote.py", line 267, in _cb
    raise Remote.BatchException(excep)
lieer.remote.BatchException: <HttpError 500 when requesting https://www.googleapis.com/gmail/v1/users/mturquette%40baylibre.com/messages/157b42525542c881?format=minimal&alt=json returned "Backend Error">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mturquette/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 143, in main
    args.func (args)
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 239, in push
    self.remote.get_messages (gids, _got_msgs, 'minimal')
  File "/Users/mturquette/src/gmailieer/lieer/remote.py", line 110, in func_wrap
    return func (self, *args, **kwargs)
  File "/Users/mturquette/src/gmailieer/lieer/remote.py", line 314, in get_messages
    raise Remote.BatchException ("cannot reduce request any further")
lieer.remote.BatchException: cannot reduce request any further
```

Is reducing batch request size to zero a bug? Thanks!

**Comment by gauteh** [comment]
Hi,

Weird, what version are you running? I think I fixed 0 batch sizes in 
405e740. Anyway, there is usually something wrong somewhere when you see 
rapid reduction in batch sizes. Could be temporary issues with the GMail 
API servers, or maybe some quota you hit.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 3, 2018 7:45:
> Weird, what version are you running? I think I fixed 0 batch sizes in 
> 405e740. Anyway, there is usually something wrong somewhere when you see 
> rapid reduction in batch sizes. Could be temporary issues with the GMail 
> API servers, or maybe some quota you hit.
> 
 
Now gradually increasing batch request sizes back to normal after 10 ok requests.

**Comment by gauteh** [comment]
I think this is fixed in a later version.
