### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u0394' in position 16: ordinal not in range(128)

### ISSUE THREAD

**Issue by mturquette** [gauteh/gmailieer#82]
I'm sometimes getting the titular error when running `gmi pull` from a cron job. Looking at my logs from yesterday, I was able to run my mail fetch script every half hour from 12:30 to 16:30 without problems. Starting at 16:30 I got the following types of errors below:

```
Fri May 25 08:01:47 PDT 2018
pull: partial synchronization.. (hid: 40692012)
fetching changes .......................done: 2065 its in 04.615s
resolving changes (2065) .................................................................................................................................................................................................................done: 2065 its in 00.041s
receiving content (32) ......done: 32 its in 05.144s
Traceback (most recent call last):
  File "/Users/mturquette/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 149, in main
    args.func (args)
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 345, in pull
    self.partial_pull ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 494, in partial_pull
    bar = tqdm (total = len(labels_changed), leave = True, desc = 'updating tags (0\u0394)')
  File "/Users/mturquette/src/gmailieer/lieer/nobar.py", line 15, in __init__
    print (desc, '(%d)' % total, '...', end = '', flush = True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0394' in position 16: ordinal not in range(128)


Fri May 25 08:30:09 PDT 2018
pull: partial synchronization.. (hid: 40692012)
fetching changes .......................done: 2095 its in 05.610s
resolving changes (2095) ....................................................................................................................................................................................................................done: 2095 its in 00.044s
receiving content (30) ......done: 30 its in 09.639s
Traceback (most recent call last):
  File "/Users/mturquette/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 149, in main
    args.func (args)
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 345, in pull
    self.partial_pull ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 494, in partial_pull
    bar = tqdm (total = len(labels_changed), leave = True, desc = 'updating tags (0\u0394)')
  File "/Users/mturquette/src/gmailieer/lieer/nobar.py", line 15, in __init__
    print (desc, '(%d)' % total, '...', end = '', flush = True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0394' in position 16: ordinal not in range(128)


Fri May 25 09:00:00 PDT 2018
pull: partial synchronization.. (hid: 40692012)
fetching changes ........................done: 2159 its in 04.142s
resolving changes (2159) ..........................................................................................................................................................................................................................done: 2159 its in 00.046s
receiving content (44) .......done: 44 its in 02.934s
Traceback (most recent call last):
  File "/Users/mturquette/src/gmailieer/gmi", line 8, in <module>
    g.main ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 149, in main
    args.func (args)
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 345, in pull
    self.partial_pull ()
  File "/Users/mturquette/src/gmailieer/lieer/gmailieer.py", line 494, in partial_pull
    bar = tqdm (total = len(labels_changed), leave = True, desc = 'updating tags (0\u0394)')
  File "/Users/mturquette/src/gmailieer/lieer/nobar.py", line 15, in __init__
    print (desc, '(%d)' % total, '...', end = '', flush = True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0394' in position 16: ordinal not in range(128)
```

My crontab:

```
crontab -l
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# fetch gmail, update notmuch tags, sync patchwork state, update gmail labels
*/30 * * * *  ~/.config/alot/hooks/cron.sh
```

cron.sh:

```
#!/bin/bash

PATH=~/.config/alot/hooks:~/src/gmailieer:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

echo >> /tmp/gmailieer_patchwork_notmuch.log
echo >> /tmp/gmailieer_patchwork_notmuch.log

set -e
cd ~/.mail/baylibre/

date >> /tmp/gmailieer_patchwork_notmuch.log
gmi pull >> /tmp/gmailieer_patchwork_notmuch.log 2>&1

date >> /tmp/gmailieer_patchwork_notmuch.log
fetch-pw-states-update-notmuch-tags.fish >> /tmp/gmailieer_patchwork_notmuch.log 2>&1

date >> /tmp/gmailieer_patchwork_notmuch.log
gmi push >> /tmp/gmailieer_patchwork_notmuch.log 2>&1

notmuch tag -new -- tag:new >> /tmp/gmailieer_patchwork_notmuch.log 2>&1
```

The fetch-pw-states-update-notmuch-tags.fish script can be found [here](https://github.com/mturquette/ghar-macos/blob/master/.config/alot/hooks/fetch-pw-states-update-notmuch-tags.fish). This script fetches state from the [patchwork](https://patchwork.kernel.org/project/linux-clk/list/) patch tracking tool and updates notmuch tags locally.

I do not see any dangling processes that could cause this problem:

```
ps -e | grep gmi; ps -e | grep notmuch
42504 ttys003    0:00.00 grep --color=auto gmi
 6208 ttys002    0:00.30 tail -f /tmp/gmailieer_patchwork_notmuch.log
42507 ttys003    0:00.00 grep --color=auto notmuch
```

Finally, simply running `gmi sync` interactively from the shell seems to fix it.

I'm currently on v0.8, 2bf01bb5f805e9a57e6a6afff297ffa338d089a6

Any thoughts on what might be going wrong? Thanks!

**Comment by mturquette** [comment]
For clarity, when I say running `gmi sync` fixes it, I mean that if I run `gmi sync` at 9:25 and it completes after 2 minutes, then the next cron job at 9:30 will complete without errors and without any other intervention on my part. Thanks!

**Comment by mturquette** [comment]
I'm on Mac OS High Sierra 10.13.4
Python aliased to version 2.7.15
Python3 version is 3.6.5

**Comment by gauteh** [comment]
Michael Turquette writes on May 25, 2018 18:33:
> I'm on Mac OS High Sierra 10.13.4
> Python aliased to version 2.7.15
> Python3 version is 3.6.5
> 

Maybe there's a python 2 thing? In Python 3 all strings are unicode -- 
so that unicode char shouldn't be a problem to represent.

https://www.b-list.org/weblog/2017/sep/05/how-python-does-unicode/

Regards, Gaute

**Comment by mturquette** [comment]
On Fri, May 25, 2018 at 9:43 AM Gaute Hope <notifications@github.com> wrote:

> Michael Turquette writes on May 25, 2018 18:33:
> > I'm on Mac OS High Sierra 10.13.4
> > Python aliased to version 2.7.15
> > Python3 version is 3.6.5
> >

> Maybe there's a python 2 thing? In Python 3 all strings are unicode --
> so that unicode char shouldn't be a problem to represent.

Please forgive my ignorant question, I'm not much of a python buff: doesn't
gmailieer require python3? I figured that python2 version wouldn't be an
issue but maybe my assumption is wrong?

Thanks,
Mike

**Comment by gauteh** [comment]
Seems that pipes don't support unicode by default. I just removed the unicode char. Please try latest master and see if it is better.

**Comment by gauteh** [comment]
I believe this should be fixed in master.

**Comment by mturquette** [comment]
I cannot tell you how sad I am to lose the Δ character :-/

But it did work. Perhaps if this change is extremely unpopular then it
could be an arg passed to gmi?

**Comment by gauteh** [comment]
I know 😕

It could be enabled conditionally based on the encoding if
sys.stdout/sys.stderr. But seemed a little complicated 😊

tir. 29. mai 2018 kl. 20:12 skrev Michael Turquette <
notifications@github.com>:
